### ISSUE TITLE
Problems when using the command createSmall

### ISSUE THREAD

**Issue by heathersherry** [IBM/cc-dbp#4]
Dear authors,

I came across a problem when trying to use the command` bash createSmall.sh`. Here is the error information:

> Exception in thread "main" java.io.IOError: java.lang.IllegalStateException: Couldn't create parent dir: configSmall.properties/kb
> 	at com.ibm.research.ai.ki.util.FileUtil.ensureWriteable(FileUtil.java:167)
> 	at com.ibm.research.ai.ki.kb.conversion.SelectRelations.downloadDBpedia(SelectRelations.java:109)
> 	at com.ibm.research.ai.ki.kb.conversion.ConvertDBpedia.main(ConvertDBpedia.java:482)
> Caused by: java.lang.IllegalStateException: Couldn't create parent dir: configSmall.properties/kb
> 	... 3 more

Could you give me some hints to solve this problem?
BTW, I have tried `mvn clean compile package install` and the build is success.

Thanks a lot!

**Comment by michaelrglass** [comment]
I updated the documentation and argument checking for the script. createSmall.sh now reports that it expects a single argument: the name of the directory to save the dataset.
